version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo start
      - sudo apt-get install sshpass
      - sshpass -p trolololo ssh pi@178.48.46.148 -p 5554
artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'