version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo start
      - ifconfig
artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'